#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include "htmlconfig.hpp"

String html(String deviceName, String b)
{
    String h = "<!DOCTYPE html>"
    "<html lang='en'>"
    "<head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>" + deviceName + " | Setting</title>"
    "<style>"
    "form,h2{margin-top:0"
   ";margin-bottom:var(-"
   "-typography-spacing-"
   "vertical);color:var("
   "--color);font-size:v"
   "ar(--font-size)}butt"
   "on,input{overflow:vi"
   "sible}button,select{"
   "text-transform:none}"
   "button,input:not([ty"
   "pe=checkbox],[type=r"
   "adio],[type=range],["
   "type=file]),select{p"
   "adding:var(--form-el"
   "ement-spacing-vertic"
   "al) var(--form-eleme"
   "nt-spacing-horizonta"
   "l)}button,details,la"
   "bel,main{display:blo"
   "ck}details summary::"
   "after,select:not([mu"
   "ltiple],[size]){back"
   "ground-image:var(--i"
   "con-chevron);backgro"
   "und-size:1rem auto;b"
   "ackground-repeat:no-"
   "repeat}:root{--font-"
   "family:system-ui,-ap"
   "ple-system,\"Segoe U"
   "I\",\"Roboto\",\"Ubu"
   "ntu\",\"Cantarell\","
   "\"Noto Sans\",sans-s"
   "erif,\"Apple Color E"
   "moji\",\"Segoe UI Em"
   "oji\",\"Segoe UI Sym"
   "bol\",\"Noto Color E"
   "moji\";--line-height"
   ":1.5;--font-weight:4"
   "00;--font-size:16px;"
   "--border-radius:0.25"
   "rem;--border-width:1"
   "px;--outline-width:3"
   "px;--spacing:1rem;--"
   "typography-spacing-v"
   "ertical:1.5rem;--blo"
   "ck-spacing-vertical:"
   "calc(var(--spacing) "
   "* 2);--block-spacing"
   "-horizontal:var(--sp"
   "acing);--grid-spacin"
   "g-vertical:0;--grid-"
   "spacing-horizontal:v"
   "ar(--spacing);--form"
   "-element-spacing-ver"
   "tical:0.75rem;--form"
   "-element-spacing-hor"
   "izontal:1rem;--nav-e"
   "lement-spacing-verti"
   "cal:1rem;--nav-eleme"
   "nt-spacing-horizonta"
   "l:0.5rem;--nav-link-"
   "spacing-vertical:0.5"
   "rem;--nav-link-spaci"
   "ng-horizontal:0.5rem"
   ";--form-label-font-w"
   "eight:var(--font-wei"
   "ght);--transition:0."
   "2s ease-in-out;--mod"
   "al-overlay-backdrop-"
   "filter:blur(0.25rem)"
   ";--scrollbar-width:0"
   "px}@media (min-width"
   ":576px){:root{--font"
   "-size:17px}article{-"
   "-block-spacing-horiz"
   "ontal:calc(var(--spa"
   "cing) * 1.25)}}@medi"
   "a (min-width:768px){"
   ":root{--font-size:18"
   "px}}@media (min-widt"
   "h:992px){:root{--fon"
   "t-size:19px}}@media "
   "(min-width:768px){ar"
   "ticle{--block-spacin"
   "g-horizontal:calc(va"
   "r(--spacing) * 1.5)}"
   "}@media (min-width:9"
   "92px){article{--bloc"
   "k-spacing-horizontal"
   ":calc(var(--spacing)"
   " * 1.75)}}:root:not("
   "[data-theme=dark]){-"
   "-background-color:#f"
   "ff;--color:hsl(205, "
   "20%, 32%);--h1-color"
   ":hsl(205, 30%, 15%);"
   "--h2-color:#24333e;-"
   "-h3-color:hsl(205, 2"
   "5%, 23%);--h4-color:"
   "#374956;--h5-color:h"
   "sl(205, 20%, 32%);--"
   "h6-color:#4d606d;--m"
   "uted-color:hsl(205, "
   "10%, 50%);--muted-bo"
   "rder-color:hsl(205, "
   "20%, 94%);--primary:"
   "hsl(195, 85%, 41%);-"
   "-primary-hover:hsl(1"
   "95, 90%, 32%);--prim"
   "ary-focus:rgba(16, 1"
   "49, 193, 0.125);--pr"
   "imary-inverse:#fff;-"
   "-secondary:hsl(205, "
   "15%, 41%);--secondar"
   "y-hover:hsl(205, 20%"
   ", 32%);--secondary-f"
   "ocus:rgba(89, 107, 1"
   "20, 0.125);--seconda"
   "ry-inverse:#fff;--co"
   "ntrast:hsl(205, 30%,"
   " 15%);--contrast-hov"
   "er:#000;--contrast-f"
   "ocus:rgba(89, 107, 1"
   "20, 0.125);--contras"
   "t-inverse:#fff;--mar"
   "k-background-color:#"
   "fff2ca;--mark-color:"
   "#543a26;--ins-color:"
   "#388e3c;--del-color:"
   "#c62828;--blockquote"
   "-border-color:var(--"
   "muted-border-color);"
   "--blockquote-footer-"
   "color:var(--muted-co"
   "lor);--button-box-sh"
   "adow:0 0 0 rgba(0, 0"
   ", 0, 0);--button-hov"
   "er-box-shadow:0 0 0 "
   "rgba(0, 0, 0, 0);--f"
   "orm-element-backgrou"
   "nd-color:transparent"
   ";--form-element-bord"
   "er-color:hsl(205, 14"
   "%, 68%);--form-eleme"
   "nt-color:var(--color"
   ");--form-element-pla"
   "ceholder-color:var(-"
   "-muted-color);--form"
   "-element-active-back"
   "ground-color:transpa"
   "rent;--form-element-"
   "active-border-color:"
   "var(--primary);--for"
   "m-element-focus-colo"
   "r:var(--primary-focu"
   "s);--form-element-di"
   "sabled-background-co"
   "lor:hsl(205, 18%, 86"
   "%);--form-element-di"
   "sabled-border-color:"
   "hsl(205, 14%, 68%);-"
   "-form-element-disabl"
   "ed-opacity:0.5;--for"
   "m-element-invalid-bo"
   "rder-color:#c62828;-"
   "-form-element-invali"
   "d-active-border-colo"
   "r:#d32f2f;--form-ele"
   "ment-invalid-focus-c"
   "olor:rgba(211, 47, 4"
   "7, 0.125);--form-ele"
   "ment-valid-border-co"
   "lor:#388e3c;--form-e"
   "lement-valid-active-"
   "border-color:#43a047"
   ";--form-element-vali"
   "d-focus-color:rgba(6"
   "7, 160, 71, 0.125);-"
   "-switch-background-c"
   "olor:hsl(205, 16%, 7"
   "7%);--switch-color:v"
   "ar(--primary-inverse"
   ");--switch-checked-b"
   "ackground-color:var("
   "--primary);--range-b"
   "order-color:hsl(205,"
   " 18%, 86%);--range-a"
   "ctive-border-color:h"
   "sl(205, 16%, 77%);--"
   "range-thumb-border-c"
   "olor:var(--backgroun"
   "d-color);--range-thu"
   "mb-color:var(--secon"
   "dary);--range-thumb-"
   "hover-color:var(--se"
   "condary-hover);--ran"
   "ge-thumb-active-colo"
   "r:var(--primary);--t"
   "able-border-color:va"
   "r(--muted-border-col"
   "or);--table-row-stri"
   "pped-background-colo"
   "r:#f6f8f9;--code-bac"
   "kground-color:hsl(20"
   "5, 20%, 94%);--code-"
   "color:var(--muted-co"
   "lor);--code-kbd-back"
   "ground-color:var(--c"
   "ontrast);--code-kbd-"
   "color:var(--contrast"
   "-inverse);--code-tag"
   "-color:hsl(330, 40%,"
   " 50%);--code-propert"
   "y-color:hsl(185, 40%"
   ", 40%);--code-value-"
   "color:hsl(40, 20%, 5"
   "0%);--code-comment-c"
   "olor:hsl(205, 14%, 6"
   "8%);--accordion-bord"
   "er-color:var(--muted"
   "-border-color);--acc"
   "ordion-close-summary"
   "-color:var(--color);"
   "--accordion-open-sum"
   "mary-color:var(--mut"
   "ed-color);--card-bac"
   "kground-color:var(--"
   "background-color);--"
   "card-border-color:va"
   "r(--muted-border-col"
   "or);--card-box-shado"
   "w:0.0145rem 0.029rem"
   " 0.174rem rgba(27, 4"
   "0, 50, 0.01698),0.03"
   "35rem 0.067rem 0.402"
   "rem rgba(27, 40, 50,"
   " 0.024),0.0625rem 0."
   "125rem 0.75rem rgba("
   "27, 40, 50, 0.03),0."
   "1125rem 0.225rem 1.3"
   "5rem rgba(27, 40, 50"
   ", 0.036),0.2085rem 0"
   ".417rem 2.502rem rgb"
   "a(27, 40, 50, 0.0430"
   "2),0.5rem 1rem 6rem "
   "rgba(27, 40, 50, 0.0"
   "6),0 0 0 0.0625rem r"
   "gba(27, 40, 50, 0.01"
   "5);--card-sectionnin"
   "g-background-color:#"
   "fbfbfc;--dropdown-ba"
   "ckground-color:#fbfb"
   "fc;--dropdown-border"
   "-color:#e1e6eb;--dro"
   "pdown-box-shadow:var"
   "(--card-box-shadow);"
   "--dropdown-color:var"
   "(--color);--dropdown"
   "-hover-background-co"
   "lor:hsl(205, 20%, 94"
   "%);--modal-overlay-b"
   "ackground-color:rgba"
   "(213, 220, 226, 0.7)"
   ";--progress-backgrou"
   "nd-color:hsl(205, 18"
   "%, 86%);--progress-c"
   "olor:var(--primary);"
   "--loading-spinner-op"
   "acity:0.5;--tooltip-"
   "background-color:var"
   "(--contrast);--toolt"
   "ip-color:var(--contr"
   "ast-inverse);color-s"
   "cheme:light}*,::afte"
   "r,::before{box-sizin"
   "g:border-box;backgro"
   "und-repeat:no-repeat"
   "}::after,::before{te"
   "xt-decoration:inheri"
   "t;vertical-align:inh"
   "erit}:where(:root){-"
   "webkit-tap-highlight"
   "-color:transparent;-"
   "webkit-text-size-adj"
   "ust:100%;-moz-text-s"
   "ize-adjust:100\%;text"
   "-size-adjust:100%;ba"
   "ckground-color:var(-"
   "-background-color);c"
   "olor:var(--color);fo"
   "nt-weight:var(--font"
   "-weight);font-size:v"
   "ar(--font-size);line"
   "-height:var(--line-h"
   "eight);font-family:v"
   "ar(--font-family);te"
   "xt-rendering:optimiz"
   "eLegibility;overflow"
   "-wrap:break-word;cur"
   "sor:default;-moz-tab"
   "-size:4;-o-tab-size:"
   "4;tab-size:4}body{wi"
   "dth:100%;margin:0}.c"
   "ontainer{width:100%;"
   "margin-right:auto;ma"
   "rgin-left:auto;paddi"
   "ng-right:var(--spaci"
   "ng);padding-left:var"
   "(--spacing)}@media ("
   "min-width:576px){.co"
   "ntainer{max-width:51"
   "0px;padding-right:0;"
   "padding-left:0}}@med"
   "ia (min-width:768px)"
   "{.container{max-widt"
   "h:700px}}@media (min"
   "-width:992px){.conta"
   "iner{max-width:920px"
   "}}@media (min-width:"
   "1200px){:root{--font"
   "-size:20px}article{-"
   "-block-spacing-horiz"
   "ontal:calc(var(--spa"
   "cing) * 2)}.containe"
   "r{max-width:1130px}}"
   ".grid{grid-column-ga"
   "p:var(--grid-spacing"
   "-horizontal);grid-ro"
   "w-gap:var(--grid-spa"
   "cing-vertical);displ"
   "ay:grid;grid-templat"
   "e-columns:1fr;margin"
   ":0}@media (min-width"
   ":992px){.grid{grid-t"
   "emplate-columns:repe"
   "at(auto-fit,minmax(0"
   "\%,1fr))}}.grid>*{min"
   "-width:0}strong{font"
   "-weight:bolder}butto"
   "n,form,h2{font-weigh"
   "t:var(--font-weight)"
   "}form{font-style:nor"
   "mal}h2{--font-weight"
   ":700;--font-size:1.7"
   "5rem;--typography-sp"
   "acing-vertical:2.625"
   "rem;font-family:var("
   "--font-family);--col"
   "or:var(--h2-color)}b"
   "utton,input,select{m"
   "argin:0;font-size:1r"
   "em;line-height:var(-"
   "-line-height);font-f"
   "amily:inherit;backgr"
   "ound-color:var(--bac"
   "kground-color);box-s"
   "hadow:var(--box-shad"
   "ow);transition:backg"
   "round-color var(--tr"
   "ansition),border-col"
   "or var(--transition)"
   ",color var(--transit"
   "ion),box-shadow var("
   "--transition);outlin"
   "e:0}::selection{back"
   "ground-color:var(--p"
   "rimary-focus)}button"
   "{width:100%;margin-b"
   "ottom:var(--spacing)"
   ";--background-color:"
   "var(--primary);--bor"
   "der-color:var(--prim"
   "ary);--color:var(--p"
   "rimary-inverse);--bo"
   "x-shadow:var(--butto"
   "n-box-shadow, 0 0 0 "
   "rgba(0, 0, 0, 0));bo"
   "rder:var(--border-wi"
   "dth) solid var(--bor"
   "der-color);border-ra"
   "dius:var(--border-ra"
   "dius);color:var(--co"
   "lor);text-align:cent"
   "er;cursor:pointer}[t"
   "ype=submit],button{-"
   "webkit-appearance:bu"
   "tton}button:focus{--"
   "box-shadow:var(--but"
   "ton-hover-box-shadow"
   ", 0 0 0 rgba(0, 0, 0"
   ", 0)),0 0 0 var(--ou"
   "tline-width) var(--p"
   "rimary-focus)}input:"
   "not([type=checkbox],"
   "[type=radio],[type=r"
   "ange]){height:calc(1"
   "rem * var(--line-hei"
   "ght) + var(--form-el"
   "ement-spacing-vertic"
   "al) * 2 + var(--bord"
   "er-width) * 2)}label"
   "{margin-bottom:calc("
   "var(--spacing) * .25"
   ");font-weight:var(--"
   "form-label-font-weig"
   "ht,var(--font-weight"
   "))}input:not([type=c"
   "heckbox],[type=radio"
   "],[type=range],[type"
   "=file]),select{-webk"
   "it-appearance:none;-"
   "moz-appearance:none;"
   "appearance:none}inpu"
   "t,select{letter-spac"
   "ing:inherit;--backgr"
   "ound-color:var(--for"
   "m-element-background"
   "-color);--border-col"
   "or:var(--form-elemen"
   "t-border-color);--co"
   "lor:var(--form-eleme"
   "nt-color);--box-shad"
   "ow:none;border:var(-"
   "-border-width) solid"
   " var(--border-color)"
   ";border-radius:var(-"
   "-border-radius);colo"
   "r:var(--color);font-"
   "weight:var(--font-we"
   "ight)}input:not([typ"
   "e=submit],[type=butt"
   "on],[type=reset],[ty"
   "pe=range],[type=file"
   "],[readonly]):focus,"
   "select:focus{--box-s"
   "hadow:0 0 0 var(--ou"
   "tline-width) var(--f"
   "orm-element-focus-co"
   "lor)}input::placehol"
   "der,select:invalid{c"
   "olor:var(--form-elem"
   "ent-placeholder-colo"
   "r);opacity:1}input:n"
   "ot([type=checkbox],["
   "type=radio]),select{"
   "width:100%;margin-bo"
   "ttom:var(--spacing)}"
   "select:not([multiple"
   "],[size]){padding-ri"
   "ght:calc(var(--form-"
   "element-spacing-hori"
   "zontal) + 1.5rem);pa"
   "dding-left:var(--for"
   "m-element-spacing-ho"
   "rizontal);-webkit-pa"
   "dding-start:var(--fo"
   "rm-element-spacing-h"
   "orizontal);padding-i"
   "nline-start:var(--fo"
   "rm-element-spacing-h"
   "orizontal);-webkit-p"
   "adding-end:calc(var("
   "--form-element-spaci"
   "ng-horizontal) + 1.5"
   "rem);padding-inline-"
   "end:calc(var(--form-"
   "element-spacing-hori"
   "zontal) + 1.5rem);ba"
   "ckground-position:ce"
   "nter right .75rem}la"
   "bel>:where(input,sel"
   "ect,textarea){margin"
   "-top:calc(var(--spac"
   "ing) * .25)}details{"
   "margin-bottom:var(--"
   "spacing);padding-bot"
   "tom:var(--spacing);b"
   "order-bottom:var(--b"
   "order-width) solid v"
   "ar(--accordion-borde"
   "r-color)}details sum"
   "mary{line-height:1re"
   "m;list-style-type:no"
   "ne;cursor:pointer;tr"
   "ansition:color var(-"
   "-transition)}details"
   " summary:not([role])"
   "{color:var(--accordi"
   "on-close-summary-col"
   "or)}details summary:"
   ":-webkit-details-mar"
   "ker{display:none}det"
   "ails summary::after{"
   "display:block;width:"
   "1rem;height:1rem;-we"
   "bkit-margin-start:ca"
   "lc(var(--spacing,1re"
   "m) * 0.5);margin-inl"
   "ine-start:calc(var(-"
   "-spacing,1rem) * .5)"
   ";float:right;transfo"
   "rm:rotate(-90deg);ba"
   "ckground-position:ri"
   "ght center;content:"
   "\"\";transition:tran"
   "sform var(--transiti"
   "on)}details summary:"
   "focus{outline:0}deta"
   "ils summary:focus:no"
   "t([role=button]){col"
   "or:var(--accordion-a"
   "ctive-summary-color)"
   "}article{margin:var("
   "--block-spacing-vert"
   "ical) 0;padding:var("
   "--block-spacing-vert"
   "ical) var(--block-sp"
   "acing-horizontal);bo"
   "rder-radius:var(--bo"
   "rder-radius);backgro"
   "und:var(--card-backg"
   "round-color);box-sha"
   "dow:var(--card-box-s"
   "hadow)}article>foote"
   "r,article>header{mar"
   "gin-right:calc(var(-"
   "-block-spacing-horiz"
   "ontal) * -1);margin-"
   "left:calc(var(--bloc"
   "k-spacing-horizontal"
   ") * -1);padding:calc"
   "(var(--block-spacing"
   "-vertical) * .66) va"
   "r(--block-spacing-ho"
   "rizontal);background"
   "-color:var(--card-se"
   "ctionning-background"
   "-color)}article>head"
   "er{margin-top:calc(v"
   "ar(--block-spacing-v"
   "ertical) * -1);margi"
   "n-bottom:var(--block"
   "-spacing-vertical);b"
   "order-bottom:var(--b"
   "order-width) solid v"
   "ar(--card-border-col"
   "or);border-top-right"
   "-radius:var(--border"
   "-radius);border-top-"
   "left-radius:var(--bo"
   "rder-radius)}article"
   ">footer{margin-top:v"
   "ar(--block-spacing-v"
   "ertical);margin-bott"
   "om:calc(var(--block-"
   "spacing-vertical) * "
   "-1);border-top:var(-"
   "-border-width) solid"
   " var(--card-border-c"
   "olor);border-bottom-"
   "right-radius:var(--b"
   "order-radius);border"
   "-bottom-left-radius:"
   "var(--border-radius)"
   "}button,input,label,"
   "select,summary{-ms-t"
   "ouch-action:manipula"
   "tion}@media (prefers"
   "-reduced-motion:redu"
   "ce){:not([aria-busy="
   "true]),:not([aria-bu"
   "sy=true])::after,:no"
   "t([aria-busy=true]):"
   ":before{background-a"
   "ttachment:initial!im"
   "portant;animation-du"
   "ration:1ms!important"
   ";animation-delay:-1m"
   "s!important;animatio"
   "n-iteration-count:1!"
   "important;scroll-beh"
   "avior:auto!important"
   ";transition-delay:0s"
   "!important;transitio"
   "n-duration:0s!import"
   "ant}}"
    "</style>"
    "</head>"
    "<body>"
    "<form action='/save' method='post' enctype='multipart/form-data' data-ajax='false'>"
    "<main class='container'>"
    "<article>" + b + "</article>"
    "</main>"
    "</form>"
    "</body>"
    "</html>";

    return h;
}

String genAccordion(String t, String b)
{
    String c = "<details open><summary><strong>" + t + "</strong></summary>" + b + "</details>";
    return c;
}

String genInput(String n, String l, String v, String t, String a)
{
    String c = "<label for='" + n + "'>" + l +
    "<input type='" + t + "' id='" + n + "' name='" + n + "' placeholder='" + l + "' value='" + v + "' " + a + ">"
    "</label>";
    return c;
}

String genOption(String v, String l, bool s)
{
    String o = "<option value='" + v + "'" + (s ? " selected" : "") + ">" + l + "</option>";
    return o;
}

String genPinOptions(uint8_t s)
{
    String o = genOption("", "Select...", !(s == D0 || s == D1 || s == D2 || s == D3 || s == D4 || s == D5 || s == D6 || s == D7 || s == D8));
    o += genOption(String(D0), "D0", s == D0);
    o += genOption(String(D1), "D1", s == D1);
    o += genOption(String(D2), "D2", s == D2);
    o += genOption(String(D3), "D3", s == D3);
    o += genOption(String(D4), "D4", s == D4);
    o += genOption(String(D5), "D5", s == D5);
    o += genOption(String(D6), "D6", s == D6);
    o += genOption(String(D7), "D7", s == D7);
    o += genOption(String(D8), "D8", s == D8);
    return o;
}

String genColorOptions(uint8_t s)
{
    String o = genOption("", "Select...", !(s == C_RED || s == C_GREEN || s == C_BLUE || s == C_PURPLE || s == C_CYAN || s == C_YELLOW));
    o += genOption(String(C_RED), "RED", s == C_RED);
    o += genOption(String(C_GREEN), "GREEN", s == C_GREEN);
    o += genOption(String(C_BLUE), "BLUE", s == C_BLUE);
    o += genOption(String(C_PURPLE), "PURPLE", s == C_PURPLE);
    o += genOption(String(C_CYAN), "CYAN", s == C_CYAN);
    o += genOption(String(C_YELLOW), "YELLOW", s == C_YELLOW);
    return o;
}

String genSelect(String n, String l, String o, String a)
{
    String c = "<div>"
    "<label for='" + n + "'>" + l + "</label>"
    "<select id='" + n + "' name='" + n + "' " + a + ">" + o + "</select>"
    "</div>";
    return c;
}

String genGrid(String b)
{
    String c = "<div class='grid'>" + b + "</div>";
    return c;
}
